language: php

sudo: false

env:
  global:
    - SYMFONY_PHPUNIT_REMOVE=symfony/yaml

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    # Test LTS versions
    - php: 7.1
      env: DEPENDENCIES="dunglas/symfony-lock:^3"
    # Test unstable versions
    - php: 7.3
      env: STABILITY="dev"
  allow_failures:
    - php: 7.4snapshot

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
  - composer update $COMPOSER_FLAGS --prefer-dist --no-interaction
  - vendor/bin/simple-phpunit install

script: vendor/bin/simple-phpunit -v
