language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest" SYMFONY_DEPRECATIONS_HELPER=weak
    # Test LTS versions
    - php: 7.1
      env: DEPENDENCIES="dunglas/symfony-lock:^3"
    # Test unstable versions
    - php: 7.2
      env: STABILITY="dev"
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
  - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install: composer update $COMPOSER_FLAGS --prefer-dist --no-interaction

script: phpunit -v
